// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// InitializeUserService 是 Wire 的注入器函数
// 它会解析依赖图并生成依赖初始化代码
func InitializeUserService() *UserService {
	database := NewDatabase()
	userRepository := NewUserRepository(database)
	userService := NewUserService(userRepository)
	return userService
}
